# Configurations
site_name: Go Notes
site_url: https://hlop3z.github.io/go-learn/
repo_url: https://github.com/hlop3z/go-learn/
copyright: Copyright © hlop3z

# Path Watch
watch:
  - overrides

# Extras
extra_css:
  - css/extra.css
  - plugins/prism/style.css

extra_javascript:
  - plugins/prism/index.js

# Navigation
nav:
  - Go Lang:
      - Commands: index.md
      - Types: types.md
      - Variables: variables.md
      - Naming: naming_conventions.md
      - Docstring: docstring.md
      - Basics:
          - Strings: strings.md
          - DateTime: datetime.md
          - IF (Statement): if-blocks.md
          - For (Loops): for-loops.md
          - Union/Any: union-any.md
      - Numbers:
          - Limits: numbers/limits.md
      - File:
          - Read/Write: files/files.md
          - Encoders: files/encoders.md
          - JSON: files/json_load_dump.md
          - HTML: files/html_templates.md
      - Pythonic:
          - Any/Dict/List: pythonic/any-dict-list.md
          - Kwargs: pythonic/kwargs.md
          - Decorators: pythonic/decorators.md
          - Data Types: pythonic/data-types.md
          - Operators: pythonic/operators.md
  - Packages:
      - Layout: packages/layout.md
      - Vendors:
          - ECHO: packages/vendors/echo.md
          - GORM: packages/vendors/gorm.md
          - GOJA: packages/vendors/goja.md
          - ESBuild: packages/vendors/esbuild.md
          - Minify: packages/vendors/minify.md

# Theme
theme:
  name: material
  custom_dir: overrides
  locale: en
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
  icon:
    logo: material/webhook

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - tables
  - attr_list

# Plugins
plugins:
  - search
